### ISSUE TITLE
RTC Ansteuerung über I2C

### ISSUE THREAD

**Issue by Fuddibaeggli** [BBZ-InformatikGrundlagen/YourTimeHasCome#1]
Ansteuerung der Pins 19 resp. 20 und Read/ Write Befehl löst Fehlercode 090 aus 

<html>
<body>

Error number | What this means
-- | --
010 | The micro:bit's I2C bus is not working. The device might be physically damaged.
020 | There is no free memory on the micro:bit. Your program might be too complex or contain a lot of large variables.          Try reducing your code by making functions out of large sections.
030 | Corruption detected in the micro:bit heap space (memory allocated usually for the storage of variables).          Try flashing a different .hex file to your device
040 | Your micro:bit can't execute your script properly. Flash a different .hex file to it, then try flashing and running your previous script again.
042 | Your micro:bit can't execute your script properly. Flash a different .hex file to it, then try flashing and running your previous script again.
043 | An error occurred with the micro:bit's radio component.
050 | An error occurred with the micro:bit's accelerometer component.
051 | An error occurred with the micro:bit's magnetometer component.
090 | The actual board hardware doesn’t match the configuration description. This can occur if a sensor is initialised multiple times in he
098 | Assertion failed. A MakeCode error that occurs when the condition in an assert was false.

**Comment by Mobileplayers** [comment]
Problem fixed.

Wrong usage of I2C bus on Lancester university.
Created two functions:

clockWriteData
clockReadData
